### ISSUE TITLE
Update compatibility information

### ISSUE THREAD

**Issue by r-valyar** [wyrmisis/bx-factions#1]
It looks like the foundry interface in v11 shows the module with unknown compatibility. I presume adding the whole json structure under compatibility will satisfy the user interface to make it green. Not on machine where I can propose a PR:

```
	"compatibility": {
		"minimum": "11",
		"verified": "11",
		"maximum": "11"
	},
```

![image](https://github.com/wyrmisis/bx-factions/assets/63558984/c5a9dc7d-5c1b-4adc-a460-3f54080356eb)

**Comment by wyrmisis** [comment]
Holy heck, so sorry it took me this long to get around to this one @r-valyar ! This should be fixed in [0.1.1](https://github.com/wyrmisis/bx-factions/releases/tag/0.1.1)!
