### ISSUE TITLE
Suggestion:  Add Faction Alignment Tracker for Good/Evil

### ISSUE THREAD

**Issue by SophieScott12** [wyrmisis/bx-factions#11]
The Factions sheet has a tracker for whether a faction is Lawful, Neutral, or Chaotic.  It would be helpful if there was also one for Good, Neutral, and Evil.

**Comment by wyrmisis** [comment]
This isn't a bad idea for people who play AD&D/OSRIC. Once I'm able to do more Foundry stuff again, I'll see if I can't add this into the module as a setting (defaulting to off, given the module's bias for Basic/Expert D&D)

**Comment by wyrmisis** [comment]
@SophieScott12 I just cut a new release (0.3.7) that should include this.
