### ISSUE TITLE
Please do not declare a global Handlebars helper with a generic name like `partial`

### ISSUE THREAD

**Issue by reonZ** [wyrmisis/bx-factions#13]
Today a user reported to me that this module was breaking one of mine and it so happen that this is because the `partial` Handlebars helper is overriding one of my template function, while i can make changes on my end, it is advised to not use such a generic name which is bound to conflict with other modules/systems.

Handlebars helpers are global to the whole foundry.

**Comment by wyrmisis** [comment]
Oh heck, sorry about that. I'll get that fixed (and a release with said fix) out in the next day or so. Should be a fairly simple find/replace.

**Comment by wyrmisis** [comment]
Annnnd updated. Thanks for the heads up!
