### ISSUE TITLE
version 0.3.8 broke visualization of pages

### ISSUE THREAD

**Issue by r-valyar** [wyrmisis/bx-factions#14]
I am running Forbidden Lands and use the module to create pages for all castle, villages etc. I am using one journal to host all castles for example, page per castle. After the update, I am no longer able to click and open pages down the list after the second-third. I had to rollback the module from backup in order to restore the functionality

![image](https://github.com/user-attachments/assets/8bf17a2d-ba8e-4c7e-9e44-c23aada55915)

**Comment by wyrmisis** [comment]
Yikes -- that's not good. Looks like I missed two templates while fixing #13 .

Gimme a few, I'll have a new release up for 0.3.8. Thanks for calling this out.

**Comment by wyrmisis** [comment]
Annnnd done. Let me know if upgrading to 0.3.8 fixes it for you.

**Comment by r-valyar** [comment]
I updated the module to 0.3.8 and now I am able to open all pages now. Thanks for the quick fix!
