### ISSUE TITLE
[ Enhancement ] Opening entities on Dungeon Room Key

### ISSUE THREAD

**Issue by Wotn9** [wyrmisis/bx-factions#3]
First off, I love it, this help to be so much efficient when describing a room in a normal dungeon crawling / exploration session. However I feel like it would be so much better if we could actually open the actors or items sheets directly from the journal entry.  Is it possible to achieve ?

**Comment by wyrmisis** [comment]
Hey! I'm glad you're finding the module helpful.

I'm *pretty sure* I added functionality for this in release 0.3.1. Have you updated your modules recently? If so, could you do me a favor and check for any JavaScript errors?

**Comment by Wotn9** [comment]
Apologies. I did not updated it (Since I had a session the day you made the update, you know" do not update before a session " ) All is working well thanks for your dedication !
