### ISSUE TITLE
Update compatibility for FVTT v12

### ISSUE THREAD

**Issue by r-valyar** [wyrmisis/bx-factions#9]
I've been using the module heavily and with V12 out for some months I think it is good to have the module updated for v12. 
I didn't see issue with the module in v12 instance of the world, so it should be pretty safe to update the version.

**Comment by wyrmisis** [comment]
Hey! Sorry about not getting back to you sooner.

I haven't put the module through its paces in v12 yet, as I haven't updated my own Foundry installs. My "fun" dev time's been limited this year, so I've struggled to get updates made to this module (or contribute to the OSE system).

I'll try to get to this once I've got the brain space for it. I appreciate your patience :slightly_smiling_face:

**Comment by r-valyar** [comment]
No rush, glad you still have this on the radar and will get update :)

**Comment by wyrmisis** [comment]
As of 0.3.7, this should be marked as compatible.
